<?php

use Drupal\quiz\Entity\QuizEntityType;
use Drupal\quiz\Entity\Result;
use Drupal\quiz\Quiz;

/**
 * @file
 * Quiz Module
 *
 * This module allows the creation of interactive quizzes for site visitors.
 *
 * Where possible, user pages are located in quiz.pages.inc, and admin pages
 * are in quiz.pages.inc. Most utility functions have been left here, even if they
 * are only used by a function in one of the other files. quiz_datetime.inc holds
 * some additional date/time functions.
 *
 * Themes are in quiz.pages.inc unless they clearly only apply to admin screens.
 * Then they are in quiz.pages.inc.
 *
 * Views support is included in includes/views/quiz.views.inc
 *
 * Functions start with __quiz_ will be removed.
 */
define('QUIZ_VIEWS_DIR', drupal_get_path('module', 'quiz') . '/includes/views');

/**
 * Include hook implementations.
 */
require_once dirname(__FILE__) . '/quiz.hooks.inc';

/*
 * Define question statuses…
 */
define('QUESTION_RANDOM', 0);
define('QUESTION_ALWAYS', 1);
define('QUESTION_NEVER', 2);

/**
 * Quiz name.
 */
define('QUIZ_NAME', _quiz_get_quiz_name());

/**
 * Define options for keeping results.
 */
define('QUIZ_KEEP_BEST', 0);
define('QUIZ_KEEP_LATEST', 1);
define('QUIZ_KEEP_ALL', 2);

/**
 * Factory to create quiz helpers wrapper.
 *
 * @staticvar Quiz $quiz
 * @param string $className
 * @return \Drupal\quiz\Quiz
 */
function quiz($className = 'Drupal\quiz\Quiz') {
  static $obj;
  return null === $obj ? ($obj = new $className) : $obj;
}

/**
 * Get controller for quiz entity.
 *
 * @return \Drupal\quiz\Entity\QuizEntityController
 */
function quiz_controller() {
  return entity_get_controller('quiz_entity');
}

/**
 * Get controller for quiz result entity.
 *
 * @return \Drupal\quiz\Entity\ResultController
 */
function quiz_result_controller() {
  return entity_get_controller('quiz_result');
}

/**
 * Get controller for answer entity.
 *
 * @return \Drupal\quiz\Entity\AnswerController
 */
function quiz_answer_controller() {
  return entity_get_controller('quiz_result_answer');
}

/**
 * Gets an array of all quiz types, keyed by the type name.
 *
 * @return \Drupal\quiz\Entity\QuizEntityType[]
 */
function quiz_get_types() {
  return entity_load_multiple_by_name('quiz_type');
}

/**
 * Get quiz-type by machine name.
 *
 * @param string $name
 * @return \Drupal\quiz\Entity\QuizEntityType
 */
function quiz_type_load($name) {
  $type = entity_load_multiple_by_name('quiz_type', array($name));
  return isset($type[$name]) ? $type[$name] : null;
}

/**
 * Load quiz entity
 *
 * @return \Drupal\quiz\Entity\QuizEntity
 */
function quiz_load($id = NULL, $vid = NULL, $reset = FALSE) {
  if (NULL === $vid) {
    return entity_load_single('quiz_entity', $id);
  }

  $results = entity_load('quiz_entity', array(), array('vid' => $vid), $reset);
  if (!empty($results)) {
    return reset($results);
  }
}

/**
 * Shortcut to entity_load_single().
 *
 * @return \Drupal\quiz\Entity\Result
 */
function quiz_result_load($result_id) {
  return entity_load_single('quiz_result', $result_id);
}

/**
 * This function was copied from the triggers module as to prevent having to be
 * dependent on that module for the actions to work.  The trigger function is
 * called trigger_options().
 *
 * @param $type
 *   One of 'node', 'user', 'comment'.
 *
 * @return
 *   Array keyed by action ID.
 */
function quiz_action_options($type = 'all') {
  $options = array(t('Choose an action'));
  foreach (actions_actions_map(actions_get_all_actions()) as $aid => $action) {
    $options[$action['type']][$aid] = $action['label'];
  }

  if ('all' === $type) {
    return $options;
  }

  $options[$type][0] = t('Choose an action');
  ksort($options[$type]); # Sort to get the choose an action back first
  return $options[$type];
}

/**
 * Finds out if a quiz has been answered or not.
 *
 * @return
 *   TRUE if there exists answers to the current question.
 */
function quiz_has_been_answered($quiz) {
  return quiz()->getQuizHelper()->isAnswered($quiz);
}

/**
 * Action to add questions to the current quiz.
 */
function quiz_add_question_to_quiz($question) {
  $quiz = quiz_load(__quiz_get_context_id());
  return quiz()->getQuizHelper()->addQuestion($quiz, $question);
}

/**
 * Updates the max_score property on the specified quizzes
 *
 * @param $quiz_vids
 *  Array with the vid's of the quizzes to update
 */
function quiz_update_max_score_properties($quiz_vids) {
  return quiz()->getQuizHelper()->updateMaxScoreProperties($quiz_vids);
}

/**
 * @param string $question_type
 *
 * @return string
 *   Name of module matching the question type, as given by quiz_question_info()
 *   hook.
 */
function quiz_question_module_for_type($question_type) {
  return quiz()->getQuizHelper()->getQuestionModuleFromType($question_type);
}

/**
 * Check if the question has already been answered in the requested attempt.
 *
 * @return bool
 *   TRUE if the question has been answered in the attempt.
 */
function quiz_result_is_question_answered($result, $question) {
  if ($answer = quiz_answer_controller()->loadByResultAndQuestion($result->result_id, $question->vid)) {
    return !empty($answer->answer_timestamp);
  }
  return FALSE;
}

/**
 * Helper function to faciliate icon display, like "correct" or "selected".
 */
function quiz_icon($icon) {
  return theme('quiz_answer_result', array('type' => $icon));
}

// ---------------------
//  Internal functions
// ---------------------

/**
 * Helper function used when validating integers.
 *
 * @param $value
 *   The value to be validated.
 * @param $min
 *   The minimum value $value is allowed to be.
 * @param $max
 *   The maximum value $value is allowed to be.
 *
 * @return
 *   TRUE if integer in the allowed range. FALSE otherwise.
 */
function _quiz_is_int($value, $min = 1, $max = NULL) {
  $to_return = ((string) $value === (string) (int) $value);

  if (!$to_return) { // $value is not an integer.
    return FALSE;
  }

  if ($value < $min) { // $value is too small.
    return FALSE;
  }

  if (isset($max) && $value > $max) { // $value is too big.
    return FALSE;
  }

  return TRUE; // $value is an integer in the allowed range.
}

/**
 * Get the quiz name variable and set it as a constant so we don't have to keep
 * calling it in every function.
 *
 * @return
 *   Quiz name variable.
 */
function _quiz_get_quiz_name() {
  return t(variable_get('quiz_name', 'Quiz'));
}

function __quiz_get_context_id() {
  return (int) arg(1);
}
