<?php

use Drupal\quiz_question\Entity\Question;

/**
 * Quiz Question module.
 * This module provides the basic facilities for adding quiz question types to a quiz.
 * @file
 */
/*
 * The system remembers what quizzes a user has been involved in lately. This constant determines
 * how many quizzes the system will remember for each user
 */
define('QUIZ_QUESTION_NUM_LATEST', 10);

/**
 * Include hook implementations.
 */
require_once dirname(__FILE__) . '/quiz_question.hooks.inc';
require_once dirname(__FILE__) . '/quiz_question.todo.php';

/**
 * Get the information about various implementations of quiz questions.
 *
 * @param string $name
 *  Name of question type.
 * @param boolean $reset
 *  If this is true, the cache will be reset.
 * @return
 *  An array of information about quiz question implementations.
 * @see quiz_question_quiz_question_info() for an example of a quiz question info hook.
 */
function quiz_question_get_plugin_info($name = NULL, $reset = FALSE) {
  $info = &drupal_static(__FUNCTION__, array());

  if (empty($info) || $reset) {
    foreach (module_invoke_all('quiz_question_info') as $type => $definition) {
      if (!empty($definition['question provider'])) { # We only want the ones with classes.
        $info[$type] = $definition;
      }
    }
    drupal_alter('quiz_question_info', $info);
  }

  // Question provider must be instance of QuizQuestion class.
  foreach ($info as $plugin_name => $plugin_info) {
    if (!is_subclass_of($plugin_info['question provider'], 'Drupal\quiz_question\QuestionPlugin')) {
      $msg = t("The question-type %name isn't a QuizQuestion. It needs to extend the QuizQuestion class.", array('%name' => $plugin_name));
      drupal_set_message($msg, 'error', FALSE);
    }
  }

  return NULL !== $name ? $info[$name] : $info;
}

/**
 * Get module for a question type.
 *
 * @param string $question_type_name
 * @return string
 *   Name of module matching the question type, as given by quiz_question_info()
 *   hook.
 */
function quiz_question_module_for_type($question_type_name) {
  $question_type = quiz_question_type_load($question_type_name);
  $plugin_info = quiz_question_get_plugin_info($question_type->plugin);
  return $plugin_info['module'];
}

/**
 * Figure out if a user has access to score a certain result
 *
 * @param $vid
 *  Question version id
 * @param $result_id
 *  Result id
 * @return
 *  True if the user has access to score the result
 */
function quiz_question_access_to_score($vid, $result_id) {
  global $user;

  $sql = 'SELECT *'
    . ' FROM {quiz_results_answers}'
    . ' WHERE result_id = :result_id AND question_vid = :question_vid';
  if (!$answer = db_query($sql, array(':result_id' => $result_id, ':question_vid' => $vid))->fetch()) {
    return FALSE;
  }

  if (user_access('score any quiz')) {
    return TRUE;
  }

  if (user_access('score taken quiz answer')) {
    $sql = 'SELECT uid FROM {quiz_results} qnr WHERE qnr.result_id = :result_id';
    if ($user->uid == db_query($sql, array(':result_id' => $result_id))->fetchField()) {
      return TRUE;
    }
  }

  if (user_access('score own quiz')) {
    $sql = 'SELECT r.uid'
      . ' FROM {node_revision} r'
      . ' JOIN {quiz_results} qnr ON (r.nid = qnr.nid)'
      . ' WHERE qnr.result_id = :result_id';
    return $user->uid == db_query($sql, array(':result_id' => $result_id))->fetchField();
  }
}

/**
 * Get an instance of a quiz question.
 *
 * Get information about the class and use it to construct a new
 * object of the appropriate type.
 *
 * @param Question $question
 *  Question entity
 * @param bool $cache
 *  Can we use a cached version of the node?
 * @return \Drupal\quiz_question\QuestionPlugin
 *  The appropriate QuizQuestion extension instance
 */
function quiz_question_get_provider(&$question, $cache = FALSE) {
  $plugins = &drupal_static(__FUNCTION__, array());

  $question_vid = isset($question->vid) ? $question->vid : 0;
  if ($cache && isset($plugins[$question_vid])) {
    return $plugins[$question_vid];
  }

  if (!isset($question->type)) {
    $question = quiz_question_entity_load(NULL, $question->vid);
  }

  // @TODO: Remove debugging code
  if (!$question instanceof Question) {
    return;
  }

  // No cached instance of QuizQuestion has been returned. We construct a new instance
  $plugin_info = $question->getPluginInfo();
  if (!$constructor = $plugin_info['question provider']) {
    return FALSE;
  }

  return $plugins[$question_vid] = new $constructor($question);
}

/**
 * Get the max score for a question
 *
 * @param $question_qid
 * @param $question_vid
 * @return
 *  Max score(int)
 */
function quiz_question_get_max_score($question_qid, $question_vid) {
  return db_query('SELECT max_score FROM {quiz_question_revision} WHERE qid = :qid AND vid = :vid', array(
        ':qid' => $question_qid,
        ':vid' => $question_vid
    ))->fetchField();
}

/**
 * Returns a result report for a question response.
 *
 * The retaurned value is a form array because in some contexts the scores in the form
 * is editable
 *
 * @param Question $question
 * @return array
 *  FAPI form array
 */
function quiz_question_report_form(Question $question) {
  $answer = $question->answers[0];
  $handler = quiz_answer_controller()->getInstance($answer['result_id'], $question, $answer);

  // If need to specify the score weight if it isn't already specified.
  if (!isset($handler->question->score_weight)) {
    $vid = db_query('SELECT quiz_vid FROM {quiz_results} WHERE result_id = :rid', array(
        ':rid' => $answer['result_id']
      ))->fetchField();

    $qr_max_score = db_query('SELECT qnr.max_score
      FROM {quiz_relationship} qnr
      WHERE qnr.question_vid = :question_vid AND qnr.quiz_vid = :quiz_vid', array(
        ':question_vid' => $question->vid,
        ':quiz_vid'     => $vid
      ))->fetchField();

    if ($qr_max_score === FALSE) {
      $qr_max_score = db_query('SELECT qt.max_score
        FROM {quiz_results} qnr
         JOIN {quiz_results_answers} qnra ON (qnr.result_id = qnra.result_id)
         JOIN {quiz_terms} qt ON (qt.vid = qnr.quiz_vid AND qt.tid = qnra.tid)
         WHERE qnr.result_id = :rid AND qnra.question_nid = :qnid AND qnra.question_vid = :qvid', array(
          ':rid'  => $answer['result_id'],
          ':qnid' => $question->qid,
          ':qvid' => $question->vid
        ))->fetchField();
    }

    $handler->question->score_weight = 0;
    if (($qr_max_score != 0 && $handler->question->max_score != 0)) {
      $handler->question->score_weight = $qr_max_score / $handler->question->max_score;
    }
  }
  return $handler->getReportForm();
}

/**
 * Theme the feedback for any question type.
 */
function theme_quiz_question_feedback($variables) {
  $rows = $variables['data'];
  $headers = array_intersect_key($variables['labels'], $rows[0]);
  return theme('table', array('header' => $headers, 'rows' => $rows));
}
